import type { ErpState, Invoice } from './types'

const expertInvoices: Invoice[] = [
  {
    id: 'inv-4471',
    number: 'INV-4471',
    supplier: 'Hartmann Präzisionsteile GmbH',
    country: 'Germany',
    amount: 7200,
    description: 'CNC milling inserts – Q3 replenishment',
    due_date: '2025-10-31',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
  {
    id: 'inv-4472',
    number: 'INV-4472',
    supplier: 'Meier & Partner Logistics AG',
    country: 'Switzerland',
    amount: 1480,
    description: 'Transport services Nov – Dec 2024',
    due_date: '2025-01-15',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
  {
    id: 'inv-4473',
    number: 'INV-4473',
    supplier: 'Technix Praha s.r.o.',
    country: 'Czech Republic',
    amount: 3900,
    description: 'Maintenance contract Q4 2024',
    due_date: '2025-02-28',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
]

const newhireInvoices: Invoice[] = [
  {
    id: 'inv-4480',
    number: 'INV-4480',
    supplier: 'Hartmann Präzisionsteile GmbH',
    country: 'Germany',
    amount: 8150,
    description: 'CNC grinding wheels – annual stock',
    due_date: '2025-11-15',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
  {
    id: 'inv-4481',
    number: 'INV-4481',
    supplier: 'Böhm Consulting GmbH',
    country: 'Germany',
    amount: 640,
    description: 'IT consulting January 2025',
    due_date: '2025-01-31',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
  {
    id: 'inv-4482',
    number: 'INV-4482',
    supplier: 'Brno Industrial Supply s.r.o.',
    country: 'Czech Republic',
    amount: 2750,
    description: 'Spare parts – press line',
    due_date: '2025-03-01',
    cost_center: 'opex 4711',
    asset_number: '',
    status: 'open',
    internal_note: '',
  },
]

export const SEEDS: Record<string, ErpState> = {
  expert: { seedSet: 'expert', invoices: expertInvoices, view: 'inbox', selected_invoice_id: null },
  newhire: { seedSet: 'newhire', invoices: newhireInvoices, view: 'inbox', selected_invoice_id: null },
}
